version: "3.9"
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "avito"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
  backend:
    build: .
    ports:
      - "8080:8080"
    environment:
      SERVER_ADDRESS: "127.0.0.1:8080"
      POSTGRES_CONN: "postgres://postgres:postgres@postgres:5432/avito"
      POSTGRES_JDBC_URL: "jdbc:postgresql://postgres:postgres@postgres:5432/avito"
      POSTGRES_USERNAME: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_HOST: "postgres"
      POSTGRES_PORT: 5432,
      POSTGRES_DATABASE: "avito"
