version: "3.9"
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "avito"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
  backend:
    build: .
    ports:
      - "8080:8080"
