# Generated by Django 5.1.1 on 2024-09-10 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.UUIDField(auto_created=True, default='uuid_generate_v4()', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('serviceType', models.CharField(choices=[('Construction', 'Construction'), ('Delivery', 'Delivery'), ('Manufacture', 'Manufacture')])),
                ('status', models.CharField(choices=[('Created', 'Created'), ('Published', 'Published'), ('Closed', 'Closed')])),
                ('version', models.IntegerField(default=1)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('organizationId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organization')),
            ],
        ),
    ]
