# Generated by Django 5.1.1 on 2024-09-10 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0002_tender_owner_alter_tender_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tender',
            name='status',
            field=models.CharField(choices=[('Created', 'Created'), ('Published', 'Published'), ('Closed', 'Closed')], db_default='Created', default='Created'),
        ),
    ]
