# Generated by Django 5.1.1 on 2024-09-11 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0004_alter_tender_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenderHistory',
            fields=[
                ('tender_id', models.UUIDField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('serviceType', models.CharField(choices=[('Construction', 'Construction'), ('Delivery', 'Delivery'), ('Manufacture', 'Manufacture')])),
                ('status', models.CharField(choices=[('Created', 'Created'), ('Published', 'Published'), ('Closed', 'Closed')], default='Created')),
                ('version', models.IntegerField(default=1)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('organizationId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organization')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
        ),
    ]
