# Generated by Django 5.1.1 on 2024-09-16 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0005_tenderhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenderhistory',
            name='owner',
        ),
    ]
