# Generated by Django 5.1.1 on 2024-09-13 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0002_alter_bid_status'),
        ('core', '0002_alter_organization_type_organizationresponsible_and_more'),
        ('tenders', '0005_tenderhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='approved_count',
            field=models.IntegerField(db_default='0', default=0),
        ),
        migrations.AlterField(
            model_name='bid',
            name='status',
            field=models.CharField(choices=[('Created', 'Created'), ('Published', 'Published'), ('Canceled', 'Canceled')], default='Published'),
        ),
        migrations.CreateModel(
            name='BidHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_id', models.UUIDField()),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('status', models.CharField(choices=[('Created', 'Created'), ('Published', 'Published'), ('Canceled', 'Canceled')], default='Created')),
                ('authorType', models.CharField(choices=[('Organization', 'Organization'), ('User', 'User')])),
                ('version', models.IntegerField(db_default=1, default=1)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('approved_count', models.IntegerField(db_default='0', default=0)),
                ('authorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user')),
                ('tenderId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenders.tender')),
            ],
        ),
        migrations.CreateModel(
            name='BidReview',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('bid_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bids.bid')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
        ),
    ]
