# Generated by Django 5.1.1 on 2024-09-16 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0003_bid_approved_count_alter_bid_status_bidhistory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='status',
            field=models.CharField(choices=[('Created', 'Created'), ('Published', 'Published'), ('Canceled', 'Canceled'), ('Approved', 'Approved'), ('Declined', 'Declined')], default='Published'),
        ),
        migrations.AlterField(
            model_name='bidhistory',
            name='status',
            field=models.CharField(choices=[('Created', 'Created'), ('Published', 'Published'), ('Canceled', 'Canceled'), ('Approved', 'Approved'), ('Declined', 'Declined')], default='Created'),
        ),
        migrations.AlterModelTable(
            name='bidhistory',
            table='bid_history',
        ),
        migrations.AlterModelTable(
            name='bidreview',
            table='bid_reviews',
        ),
    ]
